package com.android.phone.recorder;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int actionbar_cancel_background = 2130837504;
        public static final int contact_avatar_180_holo = 2130837505;
        public static final int delete_listseletor = 2130837506;
        public static final int divider_vertical_gray_title = 2130837507;
        public static final int ic_add_contacts = 2130837508;
        public static final int ic_cancel_press = 2130837509;
        public static final int ic_choosed_number_bg = 2130837510;
        public static final int ic_contact_picture_holo_dark = 2130837511;
        public static final int ic_contact_picture_holo_light = 2130837512;
        public static final int ic_empty_contacts = 2130837513;
        public static final int ic_menu_add = 2130837514;
        public static final int ic_menu_add_disable = 2130837515;
        public static final int ic_menu_add_pressed = 2130837516;
        public static final int ic_menu_delete = 2130837517;
        public static final int ic_menu_delete_pressed = 2130837518;
        public static final int ic_menu_select = 2130837519;
        public static final int ic_menu_select_on = 2130837520;
        public static final int ic_menu_select_on_pressed = 2130837521;
        public static final int ic_menu_select_pressed = 2130837522;
        public static final int ic_no_call = 2130837523;
        public static final int ic_notify_record = 2130837524;
        public static final int ic_notify_voice_record = 2130837525;
        public static final int ic_notify_voice_record_theme_7 = 2130837526;
        public static final int ic_phone_sys_call_recoder = 2130837527;
        public static final int ic_public_add = 2130837528;
        public static final int ic_public_arrow_right = 2130837529;
        public static final int ic_public_back = 2130837530;
        public static final int ic_public_cancel = 2130837531;
        public static final int ic_public_delete = 2130837532;
        public static final int ic_public_delete_disable = 2130837533;
        public static final int ic_public_deselect_all = 2130837534;
        public static final int ic_public_select_all = 2130837535;
        public static final int ic_trash = 2130837536;
        public static final int list_activated_holo = 2130837537;
        public static final int list_background_holo = 2130837538;
        public static final int list_divider = 2130837539;
        public static final int list_divider_horizontal_time_axis = 2130837540;
        public static final int list_pressed = 2130837541;
        public static final int list_pressed_holo_light = 2130837542;
        public static final int list_selected_holo_light = 2130837543;
        public static final int menu_add_contacts = 2130837544;
        public static final int menu_bottom = 2130837545;
        public static final int pic_ab_number = 2130837546;
    }

    public static final class layout {
        public static final int action_bar = 2130903040;
        public static final int actionbar_editorview_customtitle = 2130903041;
        public static final int auto_record_create_number_dialog = 2130903042;
        public static final int autorecord_calllog_list = 2130903043;
        public static final int autorecord_calllog_list_item = 2130903044;
        public static final int autorecord_delete_numbers = 2130903045;
        public static final int autorecord_empty = 2130903046;
        public static final int autorecord_list_item = 2130903047;
        public static final int cust_check_box = 2130903048;
        public static final int cust_image_view = 2130903049;
        public static final int custom_actionbar_selecting = 2130903050;
        public static final int hw_phone_setting = 2130903051;
        public static final int list_item_time_axis = 2130903052;
        public static final int preference_status_summary = 2130903053;
        public static final int preference_widget_arrow = 2130903054;
        public static final int preference_widget_radiobutton = 2130903055;
    }

    public static final class anim {
        public static final int slide_down = 2130968576;
    }

    public static final class interpolator {
        public static final int cubic_bezier_interpolator_type_90_10 = 2131034112;
    }

    public static final class xml {
        public static final int record_settings = 2131099648;
    }

    public static final class array {
        public static final int CALL_AREA_THREE = 2131165184;
        public static final int CALL_AREA_FOUR = 2131165185;
    }

    public static final class color {
        public static final int empty_contacts_text_color = 2131230720;
        public static final int note_titel_text = 2131230721;
        public static final int note_date_text = 2131230722;
        public static final int cannot_clickable_color = 2131230723;
        public static final int delete_btn_text = 2131230724;
        public static final int actionbar_text_color = 2131230725;
        public static final int autorecord_user_list_noname_color = 2131230726;
        public static final int autorecord_user_list_hasname_color = 2131230727;
        public static final int button_text_color_selected = 2131230728;
        public static final int button_text_color = 2131230729;
        public static final int autorecord_list_item_name_text_color = 2131230730;
        public static final int autorecord_list_item_number_text = 2131230731;
        public static final int actionbar_editorview_text_color = 2131230732;
        public static final int actionbar_editorview_image_color = 2131230733;
        public static final int autorecord_item_separator_color = 2131230734;
        public static final int preference_title_enable_color = 2131230735;
        public static final int preference_title_disable_color = 2131230736;
        public static final int emui_gray_5 = 2131230737;
        public static final int emui_white = 2131230738;
        public static final int transparent = 2131230739;
        public static final int cancel_btn_bg = 2131230740;
        public static final int preference_title_color = 2131230741;
    }

    public static final class string {
        public static final int filter_lowpriority_pkglist = 2131296256;
        public static final int app_name = 2131296257;
        public static final int unknown_error = 2131296258;
        public static final int create_file_error = 2131296259;
        public static final int record_done_notify = 2131296260;
        public static final int open_dev_error = 2131296261;
        public static final int file_path_error = 2131296262;
        public static final int unknown = 2131296263;
        public static final int card_title_conf_call = 2131296264;
        public static final int record_settings_title = 2131296265;
        public static final int record_automatically_summary = 2131296266;
        public static final int auto_record_settings = 2131296267;
        public static final int all_numbers = 2131296268;
        public static final int user_list = 2131296269;
        public static final int add_contacts = 2131296270;
        public static final int no_users = 2131296271;
        public static final int delete_numbers = 2131296272;
        public static final int delete_numbers_title = 2131296273;
        public static final int please_wait = 2131296274;
        public static final int title_cancel = 2131296275;
        public static final int Delete = 2131296276;
        public static final int delete_select_count = 2131296277;
        public static final int all = 2131296278;
        public static final int undefined = 2131296279;
        public static final int add_from_contacts = 2131296280;
        public static final int add_from_calllog = 2131296281;
        public static final int add_by_manually = 2131296282;
        public static final int NoCalllogText = 2131296283;
        public static final int autorecordFromCreatePhoneHint = 2131296284;
        public static final int autorecordFromCreateNameHint = 2131296285;
        public static final int confirm = 2131296286;
        public static final int cancel = 2131296287;
        public static final int SelectAll = 2131296288;
        public static final int DeselectAll = 2131296289;
        public static final int NotSelected = 2131296290;
        public static final int ActionBar_MultiSelect_TalkCancel = 2131296291;
        public static final int ActionBar_MultiSelect_Selected_618 = 2131296292;
        public static final int auto_record_settings_title = 2131296293;
        public static final int record_call = 2131296294;
        public static final int record_success_notification_content = 2131296295;
        public static final int eject_memory_card_error = 2131296296;
        public static final int insufficient_memory_card_storage_in_recording = 2131296297;
        public static final int insufficient_memory_card_storage = 2131296298;
    }

    public static final class dimen {
        public static final int actionbar_cancel_layout_marginLeft = 2131361792;
        public static final int actionbar_cancel_layout_marginRight = 2131361793;
        public static final int selected_delete_lyt_height = 2131361794;
        public static final int selected_delete_lyt_paddingTop = 2131361795;
        public static final int title_width_has_attach_delete_mode = 2131361796;
        public static final int title_width_delete_mode = 2131361797;
        public static final int checkbox_icon_layout_layout_marginRight = 2131361798;
        public static final int checkbox_icon_layout_minWidth = 2131361799;
        public static final int list_item_title_lyt_layout_marginRight = 2131361800;
        public static final int list_item_icon_picture_layout_marginLeft = 2131361801;
        public static final int activity_horizontal_margin = 2131361802;
        public static final int activity_vertical_margin = 2131361803;
        public static final int empty_contacts_icon_top_margin = 2131361804;
        public static final int contact_label_empty_text_size = 2131361805;
        public static final int empty_contacts_text_top_margin = 2131361806;
        public static final int text_size_primary = 2131361807;
        public static final int text_size_secondary = 2131361808;
        public static final int list_item_padding_left = 2131361809;
        public static final int list_item_cb_padding_right = 2131361810;
        public static final int list_item_padding_top = 2131361811;
        public static final int list_item_padding_bottom = 2131361812;
        public static final int toolbar_height = 2131361813;
        public static final int autorecord_list_name_size = 2131361814;
        public static final int autorecord_user_list_noname_size = 2131361815;
        public static final int autorecord_user_list_hasname_size = 2131361816;
        public static final int preference_item_padding_start = 2131361817;
        public static final int preference_item_padding_end = 2131361818;
    }

    public static final class id {
        public static final int display_mode = 2131427328;
        public static final int title_cancel = 2131427329;
        public static final int title_delete = 2131427330;
        public static final int cancel = 2131427331;
        public static final int titleContainer = 2131427332;
        public static final int title_select_textView = 2131427333;
        public static final int selected_delete_lyt = 2131427334;
        public static final int selected_delete_number = 2131427335;
        public static final int back = 2131427336;
        public static final int title = 2131427337;
        public static final int interception_create_black_dialog = 2131427338;
        public static final int auto_record_create_phone = 2131427339;
        public static final int auto_record_create_name = 2131427340;
        public static final int auto_record_create_cancel_button = 2131427341;
        public static final int auto_record_create_ok_button = 2131427342;
        public static final int calllog_layout = 2131427343;
        public static final int calllog_list_view = 2131427344;
        public static final int no_calllog_view = 2131427345;
        public static final int loading_progressbar = 2131427346;
        public static final int calllog_checkbox = 2131427347;
        public static final int calllog_contactInfo = 2131427348;
        public static final int calllog_number_or_mark = 2131427349;
        public static final int calllog_location = 2131427350;
        public static final int select_layout_parent = 2131427351;
        public static final int select_layout = 2131427352;
        public static final int Tv_all = 2131427353;
        public static final int check = 2131427354;
        public static final int line = 2131427355;
        public static final int listholder = 2131427356;
        public static final int hwtoolbar = 2131427357;
        public static final int iv_empty = 2131427358;
        public static final int tv_empty = 2131427359;
        public static final int checkbox_icon_layout = 2131427360;
        public static final int checkbox_delete_item = 2131427361;
        public static final int people_photo = 2131427362;
        public static final int relative_number_layout = 2131427363;
        public static final int name = 2131427364;
        public static final int number = 2131427365;
        public static final int arrow = 2131427366;
        public static final int view_title = 2131427367;
        public static final int view_selected_count = 2131427368;
        public static final int setting_container = 2131427369;
        public static final int layout_time_axis = 2131427370;
        public static final int record_settings_record_auto = 2131427371;
        public static final int menu_add_from_contacts = 2131427372;
        public static final int menu_add_from_calllog = 2131427373;
        public static final int menu_manually_add = 2131427374;
        public static final int menu_batch_delete_numbers = 2131427375;
        public static final int menu_delete = 2131427376;
        public static final int menu_select_all = 2131427377;
        public static final int menu_main = 2131427378;
        public static final int menu_add_contacts = 2131427379;
        public static final int context_delete_contacts = 2131427380;
    }

    public static final class plurals {
        public static final int defined = 2131492864;
        public static final int record_success_notification_title = 2131492865;
    }

    public static final class style {
        public static final int AppBaseTheme = 2131558400;
        public static final int AppTheme = 2131558401;
        public static final int contact_empty_icon_style = 2131558402;
        public static final int AutoRecordUserListNoName = 2131558403;
        public static final int AutoRecordUserListHasName = 2131558404;
    }

    public static final class menu {
        public static final int auto_record_add_options = 2131623936;
        public static final int auto_record_user_list = 2131623937;
        public static final int auto_record_user_list_context_menu = 2131623938;
        public static final int call_log_list = 2131623939;
    }
}
